<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="7" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-10T17:12:21 IST" name="GreenKart" finished-at="2023-05-10T17:13:05 IST" duration-ms="44156">
    <groups>
    </groups>
    <test started-at="2023-05-10T17:12:21 IST" name="cart" finished-at="2023-05-10T17:12:43 IST" duration-ms="21856">
      <class name="GreenKart.Test.cart">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:GreenKart.Test.cart@5b247367]" started-at="2023-05-10T17:12:21 IST" name="launchApplication" finished-at="2023-05-10T17:12:31 IST" duration-ms="9813" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="itemCheck()[pri:0, instance:GreenKart.Test.cart@5b247367]" started-at="2023-05-10T17:12:31 IST" name="itemCheck" finished-at="2023-05-10T17:12:32 IST" duration-ms="1355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- itemCheck -->
        <test-method signature="amountCheck()[pri:0, instance:GreenKart.Test.cart@5b247367]" started-at="2023-05-10T17:12:32 IST" name="amountCheck" finished-at="2023-05-10T17:12:33 IST" depends-on-methods="GreenKart.Test.cart.itemCheck" duration-ms="243" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amountCheck -->
        <test-method signature="countCheck()[pri:0, instance:GreenKart.Test.cart@5b247367]" started-at="2023-05-10T17:12:33 IST" name="countCheck" finished-at="2023-05-10T17:12:33 IST" depends-on-methods="GreenKart.Test.cart.itemCheck" duration-ms="77" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- countCheck -->
        <test-method signature="AddToCartLabelCheck()[pri:0, instance:GreenKart.Test.cart@5b247367]" started-at="2023-05-10T17:12:33 IST" name="AddToCartLabelCheck" finished-at="2023-05-10T17:12:34 IST" depends-on-methods="GreenKart.Test.cart.amountCheck" duration-ms="1902" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddToCartLabelCheck -->
        <test-method signature="refershCheck()[pri:0, instance:GreenKart.Test.cart@5b247367]" started-at="2023-05-10T17:12:34 IST" name="refershCheck" finished-at="2023-05-10T17:12:41 IST" depends-on-methods="GreenKart.Test.cart.AddToCartLabelCheck" duration-ms="6244" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at GreenKart.Test.cart.refershCheck(cart.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refershCheck -->
        <test-method is-config="true" signature="terminate()[pri:0, instance:GreenKart.Test.cart@5b247367]" started-at="2023-05-10T17:12:41 IST" name="terminate" finished-at="2023-05-10T17:12:43 IST" duration-ms="1795" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminate -->
      </class> <!-- GreenKart.Test.cart -->
    </test> <!-- cart -->
    <test started-at="2023-05-10T17:12:43 IST" name="Header" finished-at="2023-05-10T17:12:53 IST" duration-ms="9695">
      <class name="GreenKart.Test.HeaderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:GreenKart.Test.HeaderTest@5745ca0e]" started-at="2023-05-10T17:12:43 IST" name="launchApplication" finished-at="2023-05-10T17:12:50 IST" duration-ms="6613" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LogoCheck()[pri:0, instance:GreenKart.Test.HeaderTest@5745ca0e]" started-at="2023-05-10T17:12:50 IST" name="LogoCheck" finished-at="2023-05-10T17:12:50 IST" duration-ms="97" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoCheck -->
        <test-method signature="headerLink()[pri:0, instance:GreenKart.Test.HeaderTest@5745ca0e]" started-at="2023-05-10T17:12:50 IST" name="headerLink" finished-at="2023-05-10T17:12:51 IST" duration-ms="383" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at GreenKart.Test.HeaderTest.headerLink(HeaderTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- headerLink -->
        <test-method signature="textBox()[pri:0, instance:GreenKart.Test.HeaderTest@5745ca0e]" started-at="2023-05-10T17:12:51 IST" name="textBox" finished-at="2023-05-10T17:12:51 IST" duration-ms="626" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- textBox -->
        <test-method is-config="true" signature="terminate()[pri:0, instance:GreenKart.Test.HeaderTest@5745ca0e]" started-at="2023-05-10T17:12:51 IST" name="terminate" finished-at="2023-05-10T17:12:53 IST" duration-ms="1667" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminate -->
      </class> <!-- GreenKart.Test.HeaderTest -->
    </test> <!-- Header -->
    <test started-at="2023-05-10T17:12:53 IST" name="Error" finished-at="2023-05-10T17:13:05 IST" duration-ms="11950">
      <class name="GreenKart.Test.ErrorValidiationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:GreenKart.Test.ErrorValidiationTest@5b38c1ec]" started-at="2023-05-10T17:12:53 IST" name="launchApplication" finished-at="2023-05-10T17:13:02 IST" duration-ms="9108" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="searchBox()[pri:0, instance:GreenKart.Test.ErrorValidiationTest@5b38c1ec]" started-at="2023-05-10T17:13:02 IST" name="searchBox" finished-at="2023-05-10T17:13:02 IST" duration-ms="169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchBox -->
        <test-method signature="checkoutButton()[pri:0, instance:GreenKart.Test.ErrorValidiationTest@5b38c1ec]" started-at="2023-05-10T17:13:02 IST" name="checkoutButton" finished-at="2023-05-10T17:13:03 IST" depends-on-methods="GreenKart.Test.ErrorValidiationTest.searchBox" duration-ms="1003" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at GreenKart.Test.ErrorValidiationTest.checkoutButton(ErrorValidiationTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkoutButton -->
        <test-method is-config="true" signature="terminate()[pri:0, instance:GreenKart.Test.ErrorValidiationTest@5b38c1ec]" started-at="2023-05-10T17:13:04 IST" name="terminate" finished-at="2023-05-10T17:13:05 IST" duration-ms="1549" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminate -->
      </class> <!-- GreenKart.Test.ErrorValidiationTest -->
    </test> <!-- Error -->
  </suite> <!-- GreenKart -->
</testng-results>
